import type { Metadata } from "next";

import { 
  Inter,
  Noto_Sans,
  Marcellus,
  Raleway
} from "next/font/google";

import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs'
import { ThemeProvider } from "@/components/themeprovider";
import { Suspense } from "react";
import { ModalProvider } from "@/providers/modal-provider";
import { Toaster } from "@/components/ui/sonner";
import Loading from "./loading";

const inter = Inter({ subsets: ["latin"] });
// const marcellus = Marcellus({subsets: [] });

export const metadata: Metadata = {
  title: "Sketcha",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
        <ClerkProvider>
          <body className={inter.className}>
            <Suspense fallback={<Loading />}>
              <ThemeProvider
                attribute="class"
                defaultTheme="light"
                enableSystem
                disableTransitionOnChange
              >
                <ModalProvider />
                <Toaster />
                {children}
              </ThemeProvider>
            </Suspense>
          </body>
        </ClerkProvider>
    </html>
  );
}
